### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#10]
для компонентов чье поведение задается js нужно использовать классы.
инициализация компонентов может выглядеть как-то так
 ` buttons.forEach(button => new Button(button))`  
при этом желательно придерживаться единообразного интерфейса для различных классов

**Comment by alexanderkif** [comment]
сделал

**Comment by alextsk** [comment]
ты в основном код перенес в конструктор, это не добавляет читабельности. вынеси обработчики в отдельные методы и в конструкторе их инициализируй, заодно по их именам будет понятно что они делают

заодно можно поправить css классы - по бем классы для js должны быть отдельные c префиксом и на них не должно висеть стилей

**Comment by alexanderkif** [comment]
привет. не уверен, что делаю правильно. посмотри пожалуйста на form-input.js

**Comment by alexanderkif** [comment]
или правильней со статическим методом?

**Comment by alextsk** [comment]
addEventListener должен быть в конструкторе, почему вся логика оказалась снаружи?

и нужно дать имя обратботчику, это должно выглядеть както так
```
addEventListener('click', someMeaningfulName)
...
@bind
someMeaningfulName() {
....
```

 чтобы не биндить this лучше использовать декораторы

element.parentElement.getElementsByClassName - странно вдвойне, первое - мы должны были блок передать в конструктор и ничего не знать о его родителях, второе - чуть ниже используется jQuery
 
а какую проблему решает статичный метод?

**Comment by alexanderkif** [comment]
c @bind не работает. вот этот надо ставить npm i bind-decorator? сделал по-старому. и куда префикс js- прилепить тоже не могу понять.

**Comment by alextsk** [comment]
bind любой можно, а что именно не работает?
js- лепить на элементы которые используешь в js, посмотри пример по ссылке, там их много
без jquery можно, но ты его уже используешь в этом модуле, т.е. он загружен в любом случае, почему им не пользоваться?

**Comment by alexanderkif** [comment]
префиксы вроде сделал, но как-то странно писать вот так:
```
.form-input {
    .js-form-input__text {}
    .js-form-input__button {
          &.form-input__button_error {
```
или префиксы как-то по другому в scss добавляются, просто я не нашел?

про bind. пробовал ставить bind-decorator, чтоб как аннотацию писать перед методом, но прикрутить не понял как: vs code ругается, хром не исполняет код. может что-то не то пытаюсь использовать?

**Comment by alextsk** [comment]
с префиксами чуть сложнее, класс с префиксом добавляется к основному, не заменяет его. 
```form-input__text.js-form-input__text``` 
на основном ведь стили висят. а что странно - это плата за отвязку поведения и представления, в бэм вот так оно работает

возможно проблема в том, что у тебя не установлен [плагин](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) для декораторов, а может сам бинд не рабочий, у нас многие вот этот используют, он точно работает https://github.com/developit/decko.

**Comment by alexanderkif** [comment]
привет. классы js- добавил. с bind проблема была в невнимательном чтении. добавил .babelrc и заработало. теперь form-input.js готов? или с ним еще что-то надо делать? хочу понять, как остальные классы править, чтоб меньше переписывать )

**Comment by alextsk** [comment]
this.buttonDiv.style.display = 'flex';
this.buttonDiv.style.display = 'none'; 
такие вещи лучше убирать в css, а в js класс навешивать

re - не очень имя. понятно что там может быть любая регулярка, но что-то лучше 're' можно придумать)

memoize, debounce - не используются, не нужно импортировать

а по классам да, так норм

**Comment by alexanderkif** [comment]
по form-input все поправил (я так думаю :) ), приступаю к остальным классам...

**Comment by alexanderkif** [comment]
привет. классы поправил.

**Comment by alextsk** [comment]
this.menu.classList.toggle('visible'); - visible не по БЭМ

event.stopPropagation(); - откуда берется event?

 $('.search__button', element)[0].addEventListener('click', this.searchInputNotFound); - не нужно смешивать jquery и стандартные методы, приходится два контекста в голове держать, у jquery есть свой способ повесить обработчики. это и в других файлах нужно поправить

**Comment by alexanderkif** [comment]
а обязательно jquery использовать? мне почему-то больше без него нравится, тем более что он вот так, например не работает:
$('.dropdown__input', this.parentElement)[0].val(event.target.firstChild.data);
а вот такая строка рабочая:
$('.dropdown__input', this.parentElement)[0].value = event.target.firstChild.data;
или я неправильно понял про 

> this.input.value = this.tmp; - то же самое, зачем вытаскивать элемент из контейнера, если jQ все умеет
я бы предпочел вообще без jquery писать, если возможно. и не пришлось бы 

> два контекста в голове держать

**Comment by alextsk** [comment]
не обязательно, просто либо везде либо нигде, хотя бы в пределах файла. но вообще он упрощает жизнь, jsDOM довольно коряво написан

$('.dropdown__input', this.parentElement)[0].val(event.target.firstChild.data); - не работает потому что вот этим `[0]` ты из контейнера вытащил элемент и теперь это просто DOM объект. $().val - будет работать

**Comment by alexanderkif** [comment]
а вот так опять работает
```
var dropdownInput = $('.dropdown__input', this.parentElement)[0];
$(dropdownInput).value = event.target.firstChild.data;
```

**Comment by alextsk** [comment]
логично) ты же его обратно положил в $

**Comment by alexanderkif** [comment]
хорошо. тогда как писать предпочтительней? так: `$($('.dropdown__input', this.parentElement)[0]).val(event.target.firstChild.data);` или как выше в две строки?

**Comment by alextsk** [comment]
$('.dropdown__input', this.parentElement).val(event.target.firstChild.data); а так тебе чем не нравится?

**Comment by alextsk** [comment]
вообще как я сказал можно вообще без jQ, ты сейчас его используешь только для выбора по селектору, для этого можно сделать $ = doc.querySelectorAll и не париться. однако в интернетах очень много jQшного кода, с ним лучше разобраться хотя бы чтобы читать потом

**Comment by alexanderkif** [comment]
вроде поправил

**Comment by alextsk** [comment]
`for (let dropdown of $('.dropdown__menu')) dropdown.classList.remove('dropdown__menu_visible');`
можно через each переписать

$(rippleDiv).addClass('ripple');
        rippleDiv.setAttribute("style", `top:${Y}px; left:${X}px;`);
$(rippleDiv)
.addClass('ripple')
.css(top:'', left:'')

day.innerHTML -> $day.html();
$(this.buttonDiv). - каждая обертка это вычисления, лучше сохранить один раз в переменную

menu.classList.toggle ->$menu .toggleClass()

.getAttribute -> .attr()

слайдер можно было пока и не трогать, это отдельное задание, к нему свои требования

**Comment by alexanderkif** [comment]
поправил. вроде все просмотрел, кроме слайдера.

**Comment by alextsk** [comment]
this.menu = $('.dropdown__menu', event.currentTarget)**[0]**;
**$(this.menu)**.toggleClass('dropdown__menu_visible');
старайся не оборачивать каждый раз если можно присвоить в переменную

this.input[0].value == this.input.val()

 rippleDiv.style.background = customColor; -> .css(

$(this).val() - > лучше явно брать таргет из объекта события
 $(this).datepicker

**Comment by alexanderkif** [comment]
поправил

**Comment by alexanderkif** [comment]
привет. значение для даты в календаре теперь беру из события.

**Comment by alexanderkif** [comment]
привет.возился с классами и переписал слайдер, теперь mod v.3 )))
