### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#12]
в ридми нужно добавить инструкцию для развертывания и запуска проекта. 
и я не вижу дев сервера, если его нет нужно тоже добавить.

**Comment by alexanderkif** [comment]
можешь пример дать на инструкцию? и что такое дев сервер?

**Comment by alextsk** [comment]
пример
https://github.com/chmnkh/task-4/tree/refactoring
дев сервер лучше тем, что он идет в проекте, нельзя рассчитывать что все используют какую-то конкретную IDE

**Comment by alexanderkif** [comment]
привет. ридми исправил, дев сервер добавил.

**Comment by alexanderkif** [comment]
привет. иконку еще добавил.

**Comment by alextsk** [comment]
с картинками можно много всего придумать, можно их инлайнить в сборку, собирать где то в одной папке, при сборке менять пути, тут что тебе больше нравится. это не уникальная задача, загугли webpack images)
с задержкой это костыль конечно, нужно разобраться в чем проблема, почему скрипт выполняется раньше если он должен загружаться после парсинга html?

**Comment by alexanderkif** [comment]
получилось через resolve alias.
