### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#13]
слайдер должен быть в своем отдельном репозитории и подключаться в макет как любой другой плагин. плюс по заданию для него должно быть графическое описание, а для текущей версии его придется совмещать с ридми макета и будет все запутано. давай перенесем его в отдельный реп и остальные ишью для слайдера я уже туда буду писать.

**Comment by alexanderkif** [comment]
перенес. https://github.com/alexanderkif/modifiable-slider

**Comment by alextsk** [comment]
а зачем ты его в паблик оставил? его нужно устанавливать через npm как другие модули

**Comment by alexanderkif** [comment]
не уверен, что правильно, но сделал.

**Comment by alextsk** [comment]
да, так правильно. в паблике еще остался lc_switch, его тоже так нужно подключать

**Comment by alexanderkif** [comment]
не могу сообразить, как это сделать. npm не хочет, т.к. нет package.json у него на гитхабе. если через raw ссылку в html вставлять - браузер ругается. похоже проще самому заново написать...

**Comment by alextsk** [comment]
да не, заново не надо конечно, можно сделать свой форк и в форке добавить pckage.json

**Comment by alexanderkif** [comment]
сделал.

**Comment by alextsk** [comment]
теперь в паблик осталась одна папка, есть смыл вынести ее и убрать паблик совсем

**Comment by alexanderkif** [comment]
паблик убрал.
