### ISSUE TITLE
Реализовать автоматический импорт файлов ( см. flatUI.scss, index.js)

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#18]

**Comment by alexanderkif** [comment]
сделал

**Comment by GoodDayTodayOkey** [comment]
Так не годится. 1) Вынеси все переменные в файл constants и импорть его руками где это необходимо. 2) удали комменты 3) 
![Снимок экрана от 2019-04-10 09-34-50](https://user-images.githubusercontent.com/31854808/55847563-fa498680-5b73-11e9-8b6d-ca040e1dcf07.png) 
вот это вынести в index.js, картинки импорть также автоматически. 4) Под это создай в src отдельную папку  vendors 
![Снимок экрана от 2019-04-10 09-39-15](https://user-images.githubusercontent.com/31854808/55847722-94113380-5b74-11e9-94ff-5e2e77e243e7.png)

**Comment by alexanderkif** [comment]
сделал
