### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#2]
то же что в первом проекте

**Comment by alexanderkif** [comment]
привет. сделал

**Comment by alextsk** [comment]
btn_green - слишком специфично, ты же написал btn_small а не btn_22px, 
btn_disable - disable**d**
header percentages__header(везде на header) - множество таких классов, непонятно. если это микс, то где блок percentages? если модификатор то не по бэм. в любом случае это невалидная конструкция. https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_7mb9j/
content xxxxx - то же
content search-profile - тут вообще два блока
percentage4list - ?
percentage__svg - мы видим по тегу что это свг. какую информацию это дает о смысле элемента?
header forms__tick__header - не бывает элементов элементов
a href="2.html - зачем статичная ссылка в компоненте?
messaging__message1 - это чат, там будут сотни сообщений, зачем каждому отдельный номер?
messaging__message2 - даже не сообщение, это поле ввода
messaging__hr - что такое hr?
map__slog - slog?
перечитай, пожалуйста, про [бэм,](https://ru.bem.info/methodology/) и посмотри еще раз по всем классам, я возможно не все ошибки отметил

**Comment by alextsk** [comment]
а ты gh-pages обновлял?

**Comment by alexanderkif** [comment]
привет. 
header вынес в миксин. 
content убрал. 
по кнопкам не понял пока.
по ссылке тоже не понял, передаю ее в миксин +new(...,"2.html"). внутри компонента ее нет.
со stage__svg тоже непонятно, кого в отдельные папки складывать?

**Comment by alextsk** [comment]
со stage__svg - проблема как с percentage__svg - что мы в классе ничего нового не сообщаем
а про папки это другая задача, выносить надо блоки. лежит у тебя например в index.pug блок .arrow-buttons а должен в отдельном файле и папке. посмотри как в первом макете и cv.pug их потом импортирует

**Comment by alexanderkif** [comment]
привет. 
stage__svg переименовал. 
a(href...) теперь с классом. 
блоки в папки вынес.
кнопки разделил.
if (btnlabel=='<') убрал.
данные вынес в json.

**Comment by alextsk** [comment]
стрелки сейчас не отдельный блок, это просто копия кнопок в другом файле. если файл называется arrow-button имя блока должно быть .arrow-button у них с обычными кнопками вообще кроме цвета ничего общего нет, стрелки не могут быть маленькими или разноцветными, риппл эффект им не нужен, оформи им отдельные стили. заодно они перестанут подпрыгивать при клике 

в .forms остался .content

стили &__content чтобы не копировать по элементам можно оформить как [миксин](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins) в отдельном файле и импортировать

в user-card__socials ссылки без классов

dropdown__menu-1 ?

и может компоненты выделить в отдельную поддиректорию? а то уже довольно сложно ориентироваться в src

**Comment by alexanderkif** [comment]
arrow-button поправил, риппл и нажатие убрал. content из  forms тоже убрал. ссылкам в user-card__socials классы прописал. в dropdown__menu убрал единицу. компоненты в отдельную папку переместил.

**Comment by alextsk** [comment]
ок, для БЭМа норм, это ишью закрываю
