### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#21]
Для классов тэгов которые используются в js - необходимо добавлять именование класса с префиксом js.

**Comment by alexanderkif** [comment]
добавил

**Comment by GoodDayTodayOkey** [comment]
Неверно. https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78v67/ 
Это правило также можешь сразу применять ко всему проекту в этом ишью https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78v66/

**Comment by alexanderkif** [comment]
сделал.

**Comment by alexanderkif** [comment]
сделал. насчет тех классов, что добавляются и ремувятся: среди них нет тех, которые для работы js; они только для внешнего вида из css. несколько раз просмотрел, вроде ничего не пропустил.
