### ISSUE TITLE
Магические числа

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#22]
Исключить из проекта магические числа (buttons.pug, stage.pug, selectors.pug)

**Comment by alexanderkif** [comment]
в stage убрал. в buttons.pug цикл раскрутил, если это имелось ввиду. selectors: если речь идет о sectors, то не понимаю, что там магического: размер, радиус=полразмера и пары { цвет : процент }.

**Comment by GoodDayTodayOkey** [comment]
Распускать цикл явно не стоит. Почему ты не хочешь data.json buttons в массив строк с необходимым количеством  и размерами кнопок внутри строки, а в pug реализовать цикл в цикле? В stage сделать перебор без особых первых значений, вынесенных за пределы цикла( можно разрулить стилями). Поскольку ты вставляешь числа в качестве текста перебор должен начинаться с 1.

**Comment by alexanderkif** [comment]
сделал
