### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#23]
Не использовать паддинги для позиционирования внутри блока.

**Comment by alexanderkif** [comment]
Хочу уточнить, как делать расстояние между блоками в вертикали. Маржином или паддингом, верхним или нижним, или как-то еще?

**Comment by GoodDayTodayOkey** [comment]
Блок не должен иметь ни маржинов, ни паддингов. Создаешь внутри блока элемент header к примеру и отступаешь им с помощью маржинов на такое расстояние, которое необходимо для визуального отступа между двумя блоками.

**Comment by alextsk** [comment]
паддинги блок может иметь, нельзя задавать внешнее позиционирование изнутри блока, и вот этот трюк с внутренним маржином - это и будет внешнее позиционирование. 
если речь про расстояние между блоками - значит  они лежат в элементах внешнего по отношению к ним блока - вот в этих элементах и будет паддинг.

**Comment by GoodDayTodayOkey** [comment]
Паддинги не должны использоваться для внешнего визуального позиционирования блока. Приведу пример у блока имеется рамка, и мы задали ему падинги с боков  для оттеснения элементов, а в другом месте решили добавить в этот блок еще элементов, но к ним не применять отступ от той же рамки.

**Comment by alextsk** [comment]
мне кажется, то что ты описываешь, это не проблема бэм, это наше решение так сделать блок. мы решили на этапе дизайна что паддинг там будет всегда. или потом модификатором его уберем. а внешнее позиционирование это если мы раместили блок 100х100 а он занял 150 потому что у его элемента есть маржин, который торчит за пределы блока, из-за магии маржинов) или позиционированные элементы из него торчат, закрывая соседние блоки.

**Comment by GoodDayTodayOkey** [comment]
Я не писал о варианте когда, либо есть либо нет паддингов, я описывал вариант когда нам нужно чтобы для одних элементов были паддинги, а для других нет. Предложенный мною вариант избавляет от это проблемы, и избыточных модификаторов.

**Comment by alextsk** [comment]
вариант с паддингами - это архитектурное решение, может не самое элегантное, но не противоречащее бэм. твой вариант - это прямое нарушение принципа за который ты и топишь)
расстояние между блоками можно сделать только если они лежат в элементах. или сами являются элементами, но мы миксы не используем, поэтому только первый вариант.

**Comment by GoodDayTodayOkey** [comment]
1) Пруфы будут, что мое решение противоречить бэму?) 2) Мы и в элемент можем блок вложить, так что это ничего не отменяет, как быть с паддингами если они заданы у главного блока, но нужны не для всех его элементов с вложенными блоками? Предлагаю закрыть обсуждение. Паддинги нужно убрать у блоков.

**Comment by alexanderkif** [comment]
В итоге, как делать? Я понимаю, как объясняет Алексей, но не могу сообразить как ты предлагаешь сделать отступ между блоками без маржинов и паддингов. Можешь дать ссылку на пример?

**Comment by GoodDayTodayOkey** [comment]
Убери паддинги у блоков и повесь их на элементы, можешь маржины использовать на элементах если так сподручнее будет.

**Comment by alextsk** [comment]
1

>  Создаешь внутри блока к примеру элемент header и отступаешь им с помощью маржинов на такое расстояние 

https://medium.com/fed-or-dead/margin-collapse-or-why-your-child-element-is-moving-the-parent-b199a0b60497 proof enough?) 

2 да кучу можно придумать ситуаций где паддинг мешает и где он помогает. у блока например по дизайну появится бордер, и между бордером и контентом расстояние - для этого придется использовать модификаторы, либо убирать паддинг если он был, либо ставить, если не было в базовой комплектации. бэм не запрещает оба варианта.

**Comment by alexanderkif** [comment]
отступил хидером.

**Comment by GoodDayTodayOkey** [comment]
> 1
> 
> > Создаешь внутри блока к примеру элемент header и отступаешь им с помощью маржинов на такое расстояние
> 
> https://medium.com/fed-or-dead/margin-collapse-or-why-your-child-element-is-moving-the-parent-b199a0b60497 proof enough?)
> 
> 2 да кучу можно придумать ситуаций где паддинг мешает и где он помогает. у блока например по дизайну появится бордер, и между бордером и контентом расстояние - для этого придется использовать модификаторы, либо убирать паддинг если он был, либо ставить, если не было в базовой комплектации. бэм не запрещает оба варианта.

1) это не серьзено и легко обходится паддингами на элементах. 2) Что делать если по дизайну для одних этот паддинг есть а других элементов его нет?
