### ISSUE TITLE
dropdown 

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#25]
$(window).click(this.clickOutside); лучше заменить на onblur

**Comment by alexanderkif** [comment]
инпуту блюр назначать? как тогда элементы меню выбирать? блюр закроет меню и таргетом будет инпут. а я по таргету нажатый элемент определяю.

**Comment by GoodDayTodayOkey** [comment]
Код следует писать инкапсулировано, к тому же blur можно вешать и на div. Вот статья об этом https://www.barryvan.com.au/2009/01/onfocus-and-onblur-for-divs-in-fx/                                                
НО лучше всего здесь использовать select и стилизовать его https://habr.com/ru/post/442888/ по причинам: сейчас в твоем примере можно ввести любое значение и оставить его, даже если оно не соответствует какому - либо из предложенных. Select же избавит тебя от этой головной боли)  Тебе приходится присваивать значение inputу (для сбора формой например), от этого тоже тебя избавит select.

**Comment by alexanderkif** [comment]
через readonly тоже неплохо "инкапсулируется" ) а насчет blur на div: похоже не прижилось это, судя по дате новости. на stackoverflow тысячи делают через window и $(document). а вот в варианты по ссылкам слишком заморочны и негуманны по отношению к ~~человечеству~~ тем, кто может это позже читать ) имхо

**Comment by alexanderkif** [comment]
а еще с js без readonly существует перспектива сделать фильтр по первым вводимым буквам, а значение перед присваиванием сверять со списком )

**Comment by GoodDayTodayOkey** [comment]
Под инкапсуляцией кода, я имел ввиду навешивание обработчика на window. Ты можешь, оставить свое решение, но для этого тебе нужно будет немного доработать свой блок:
1) Вешать обработчик не на window, а хотя бы на document, это связано с тестированием твоего кода. Также необходимо каждый раз навешивать его при клике на стрелку для выпадания списка и убирать при клике вне области dropdown. 2) Твой дропдаун должен обеспечивать идентичность работы нативного select. К списку доработки относятся: управление с клавы, возможность показывания несколько вариантов одновременно, осуществление множественного выбор. К тому же стоит обратить внимание на дополнительные нюансы, например, как этот элемент будет воспринимать скринридер, будет ли он работать в режиме AMP. Либо воспользоваться имеющимся нативным select и кастомизировать его.

**Comment by alexanderkif** [comment]
Заменил. Выпадающие итемы не кастомизируются. Если их заменить на что-либо другое, то нативного поведения select не получится.
