### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#27]
Использовать кастомную метку для задания местоположения.

**Comment by alexanderkif** [comment]
сделал

**Comment by GoodDayTodayOkey** [comment]
Не совпадает с макетом https://www.dropbox.com/s/9mi6ssxwzwxjvye/FlatUI.psd?dl=0 Белый ободок, скругления, размеры сделай чтобы не было расхождений пожалуйста. https://developers.google.com/maps/documentation/javascript/custom-markers

**Comment by alexanderkif** [comment]
сделал

**Comment by GoodDayTodayOkey** [comment]
Парочку замечаний:  1) вынеси js в отдельный в js файл 2) для селекта использовать класс, а не id

**Comment by alexanderkif** [comment]
сделал.
