### ISSUE TITLE
alt

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#29]
Для альта нужно придумывать осмысленную замену - 'no img' не катит)) (messaging.pug, news.pug)

**Comment by alexanderkif** [comment]
заменил

**Comment by GoodDayTodayOkey** [comment]
Альт служит для описания того что должно быть изображено на картинки, он и так выведется если ее не будет, писать об этом в альте не нужно. Оставь к примеру просто new news, либо можешь описать что, изображено на ней.

**Comment by alexanderkif** [comment]
сделал
