### ISSUE TITLE
perfect pixel

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#3]
так же как в первом проекте. 
тут довольно много расхождений с макетом, если здесь же будешь править разбивай на разные коммиты по блокам

**Comment by alexanderkif** [comment]
![image](https://user-images.githubusercontent.com/19386299/48900339-8aa85880-ee6b-11e8-813f-dccdd7ed4baa.png)

**Comment by alextsk** [comment]
привет. почти ок)
не везде подходящие семейства/размеры или веса шрифтов( подписи на кнопках, заголовки разделов, 40 в слайдере, on/off, meet us)

**Comment by alexanderkif** [comment]
вроде все поправил.

**Comment by alextsk** [comment]
некоторые заголовки по прежнему жирнее чем на макете, у тебя почему то не грузится тонкое начертание
![fonts](https://user-images.githubusercontent.com/16453186/49595976-db5f9b80-f9ab-11e8-8d9e-ea2da89eb52b.png)

**Comment by alexanderkif** [comment]
я случайно закрыл ) видимо нельзя fixed писать в коммитах. шрифты я поправил.

**Comment by alextsk** [comment]
в gh-pages нет изменений

**Comment by alexanderkif** [comment]
Published

**Comment by alextsk** [comment]
закрыто)
