### ISSUE TITLE
height для блоков

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#30]
Старайся чтобы высота блока была не захардкожена, а определялась его детьми. Таких блоков много - необходимо подправить.

**Comment by alexanderkif** [comment]
Вот это ишью перекликается с другим, которое с паддингами. Перед тем, как убрать высоту, надо сначала выяснить, чем можно делать отступы.

**Comment by GoodDayTodayOkey** [comment]
Ответил в другом ишью. Это тогда закрою, другое пусть висит.
