### ISSUE TITLE
Счетчик цикла

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/flatUI#31]
Используй для счетчиков цикла осмысленные имена, а не i (news.pug, profiles.pug, searches.pug, sliders.pug)

**Comment by alexanderkif** [comment]
сделал. в news итерации нет.

**Comment by GoodDayTodayOkey** [comment]
В forms.pug пропустил именование счетчика. В stage.pug к циклу for это тоже относится. Там сразу поменяй var на let. sectors.js убери цикл for используй перебирающие методы которые предоставляет js для этого map и т.д. в зависимости от требуемой задачи.

**Comment by alexanderkif** [comment]
сделал. но у меня сомнения насчет sectors.js: а гарантирует ли foreach порядок, ну скажем, при параллельной обработке?  в случае с итератором порядок точно будет.

**Comment by GoodDayTodayOkey** [comment]
Что ты имеешь ввиду под параллельной обработкой? В эта статья тебе поможет разобраться https://medium.com/@pavelbely/javascript-event-loop-%D0%B2-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B0%D1%85-%D1%87%D0%B0%D1%81%D1%82%D1%8C-1-a19e4d99f242 Я конечно не пользовался такой штукой но думаю что если передать псевдомассив, то порядок обхода в таком случае не будет гарантирован => Array.prototype.forEach.call(PsevdoMassive, function(){});
