### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#4]
в шапке button.pug написано 
`//- btnclass can be small theme_red|theme_green disabled`
но сейчас кнопка может быть чем угодно ведь ты разрешаешь создавать в ней любые классы параметрами, еще и склеиваешь из атрибутов, так не нужно. все возможные состояния компонента должны быть заданы явно, т.е. кнопка может быть  "small theme_red|theme_green disabled" и все. нужно новое состояние - вводим новый модификатор. на ней может быть несколько модификаторов, просто они должны быть известны заранее
компонент вызванный с неизвестным параметром должен отрисовать состояние по умолчанию

т.к. стрелки это скопированные кнопки это все и к ним относится, плюс
disabled стрелка не должна реагировать на ховер
disabled кнопок вообще нет на макете
![buttons](https://user-images.githubusercontent.com/16453186/49687012-7c2a9400-fb2f-11e8-8e48-ec559d53dd40.jpg)

ripple effect не должен вылезать за границы кнопки,
![ripple_bug](https://user-images.githubusercontent.com/16453186/49598292-e23cdd00-f9b0-11e8-8d6f-9e894634e6a1.png)
несколько эффектов подряд должны накладываться

**Comment by alexanderkif** [comment]
привет. сделал. имхо раньше было красивее )

**Comment by alextsk** [comment]
потому что наоборот) неактивные белые, на ховере залитые, тогда будет видно риппл и будет красивее)

**Comment by alexanderkif** [comment]
переделал. и disabled из js убрал.

**Comment by alextsk** [comment]
<button class="btn btn_theme_red btn_theme_red btn_small">button</button> - почему  btn_theme_red два раза повторяется?

**Comment by alexanderkif** [comment]
привет. убрал повторение
