### ISSUE TITLE
Sectors

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#5]
canvas=document.getElementById('cnvs') - почему айди? вдруг он не один на странице, плюс имя не по бэм

вообще контракт миксина не очень понятен, что такое p1,p2,p3? почему их только три? очень узко специализированный элемент получается, нужно чтобы он мог принимать произвольное количество данных, передавать с цвет с данными или компонент сам будет внутри определять - на твое усмотрение

**Comment by alexanderkif** [comment]
привет. исправлено
