### ISSUE TITLE
Stage

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#7]
вообще для такого простого компонента свг - это перебор. но тут не критично, можешь оставить если считаешь нужным. а вот класс act лучше писать полностью active, три сэкономленных буквы не сильно увеличат код. в отличие от свг) 
без pas вообще можно обойтись, просто будет значение по умолчанию без active

**Comment by alexanderkif** [comment]
привет. svg убрал, три буквы добавил )
