### ISSUE TITLE
Inputs / Search

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#8]
ERROR и THANKS не должны просто всегда висеть, они должны быть реакцией на ввод

I've not found what I'm looking for... тоже должен выпадать при нажатии на иконку например

choose an option должен подставлять выбранную опцию в поле
и добавь немного места под последним элементом, как в макете

для примера можно посмотреть как они у меня работают https://alextsk.github.io/blog-markup/ui/

**Comment by alexanderkif** [comment]
привет. сделал

**Comment by alextsk** [comment]
норм, только иконка у поиска немного съехала
