### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/flatUI#9]
календарь должен работать) по стрелкам должны меняться месяцы, при клике на дни выбираться число, при клике на today выбираться сегодняшний день. тут проще взять какой-нибудь готовый датапикер и стилизовать его

**Comment by alexanderkif** [comment]
привет. сделал

**Comment by alexanderkif** [comment]
исправил

**Comment by alextsk** [comment]
теперь тудей после нажатия всегда выбран в таблице, пусть он будет как любой другой день.
и раз нужно использовать классы, почему бы не начать с календаря)
кстати, у nodeLilst есть forEach

**Comment by alexanderkif** [comment]
подсветку тудей убрал. календарь теперь в классе. forEach слету не завелся почему-то ) через Array все норм.

**Comment by alextsk** [comment]
а почему getElementsByClassName? у тебя же есть $ там и each свой

**Comment by alexanderkif** [comment]
сделано
